---
title: "TP1 Instructions: In-Class Code Demos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Team Project 1 (TP1) Instructions

Each team is scheduled to give one code demo presentation in class. The presentation is usually on
Wednesdays for 30-40 minutes long. (Please confirm presentation date with the instructor if you're
not sure.)

The presentation includes two parts:

1. The assigned lab(s) from the textbook (15-20 minutes)
Note: If you're checking your work against the solutions posted by the authors,
you might get slightly different numbers, because you're using a newer version of
R

2. One applied (not conceptual) exercise from the chapter (15-20 minutes)
  - The team gets to choose an exercise
  - The exercise should be relevant to the assigned lab(s)
  - If parts of the exercise are out of the scope relative to the team's assigned lab(s)
    from above, the team can feel free to skip those parts
  
The team will also create a Poll question based on the demo

Deliverables

One week before the presentation: The team captain should email the instructor the team's
choice of Applied Exercise

One day before the presentation, the team captain should

1. Email the instructor one Poll question based on the presentation. The question should be on a
concept or skill, preferably about R, that the students should know already that is going to be used
in some important way in your coding presentation.

2. Submit in Blackboard the link to the team's GitHub page with commented code for both parts.
You don't need to finish your work before submitting the link. The instructor will not grade the page
until after the presentation. However, submitting early allows the instructor to post your link on
the External Course Website so that the class can access the link directly during presentation.

Presentation Format

The TP1 presentation will typically take place during the second half of a class meeting, when only
one team is scheduled. The instructor will begin class with the attendance poll, give a lecture, and
then reserve the last 30-40 minutes of class time for the TP1 presentation. On rare occasions, two
TP1 presentations will be scheduled for the same day. When that happens, there will be no lecture.
The class will begin with the attendance poll and proceed directly to the TP1 presentations.

Present your work using some sort of Notebook/R Markdown. Avoid presenting code directly from
RStudio (it's difficult to read from the audience.)

Each presentation should be organized into 6 parts:

  1. Objectives: What problem are we trying to solve?
  2. Dataset: Is this a real dataset? simulated dataset? Briefly explain the Xs and Ys
  3. Explore the dataset: Key highlights - Correlations? summary statistics? Plots?
  4. Feature engineering: Do you have to transform variables? log/scale/polynomials?
  5. Train/test the model: Emphasize the new library/command you're introducing here, and
  key tuning parameters (e.g., lambda)
  6. Evaluate the model: What metrics are you using? Are you tuning any parameters? Plots?

All team members should contribute to the preparation of the presentation. However, the team can
decide who to give the presentation. You can distribute the presentation work evenly, or you can
just have one person presenting on the team's behalf.

All team members should be on the stage supporting the presenter(s) and be ready to handle
questions.

The team should try its best to engage the audience - ask questions before revealing the answers,
ask class to guess the next line of code before revealing it, get the class to think critically, try a
different method from previous lessons, compare and contrast different methods, quiz the class
about how to modify the code for a different scenario, etc

Grading Rubric

  - Explanation: Does the team explain the code well? The presenter should try to connect
    the code to relevant concepts from the lecture/textbook, and connect the Applied
    Exercise to the lab/chapter material
  - Engagement: Does the presentation engage the audience effectively using a Q&A
    format? Does the team get the class to think critically? Is the Poll question thoughtful?
  - Preparation: Is the team well prepared for the presentation and Q&A? Does the team
    handle questions well? Is the code GitHub page organized, well documented, and well
    designed?
